git-debimport cyrus-sasl2_2.1.25.dfsg1-6+deb7u1.debian.tar.gz

diff --git a/debian/sasl2-bin.saslauthd.init b/debian/sasl2-bin.saslauthd.init
--- a/debian/sasl2-bin.saslauthd.init
+++ b/debian/sasl2-bin.saslauthd.init
@@ -64,6 +64,17 @@ do_reloadall()
 	done
 }
 
+# Function that sends a SIG0 to all saslauthd instances
+# Parameters: none
+# Return value: none
+do_checkall()
+{
+	for instance in $DEFAULT_FILES
+	do
+		check_instance $instance
+	done
+}
+
 # Function that starts a single saslauthd instance
 # Parameters:
 #	$1 = path of default file for this instance
@@ -90,12 +101,18 @@ start_instance()
 
 	log_daemon_msg "Starting $DESC" "$NAME"
 
+	# Set OPTIONS to a default value, as noted in the defaults file
+	if [ -z "$OPTIONS" ]; then
+		log_warning_msg "Options (OPTIONS) undefined in $1, using default (-c -m /var/run/saslauthd)"
+		OPTIONS="-c -m /var/run/saslauthd"
+	fi
+
 	# Determine run directory and pid file location by looking
 	# for an -m option.
 	RUN_DIR=`echo "$OPTIONS" | xargs -n 1 echo | sed -n '/^-m$/{n;p}'`
 	if [ -z "$RUN_DIR" ]; then
 		# No run directory defined in defaults file, fail.
-        log_failure_msg "No run directory defined for $NAME, not starting"
+                log_failure_msg "No run directory defined for $NAME (did you forget to set OPTIONS=\"-c -m /var/run/saslauthd\" in the defaults file?), not starting"
 		return 1
 	fi
 	PIDFILE=$RUN_DIR/saslauthd.pid
@@ -172,12 +189,18 @@ stop_instance()
 		NAME=default
 	fi
 
+	# Set OPTIONS to a default value, as noted in the defaults file
+	if [ -z "$OPTIONS" ]; then
+		log_warning_msg "Options (OPTIONS) undefined in $1, using default (-c -m /var/run/saslauthd)"
+		OPTIONS="-c -m /var/run/saslauthd"
+	fi
+
 	# Determine run directory and pid file location by looking
 	# for an -m option.
 	RUN_DIR=`echo "$OPTIONS" | xargs -n 1 echo | sed -n '/^-m$/{n;p}'`
 	if [ -z "$RUN_DIR" ]; then
 		# No run directory defined in defaults file, fail.
-        log_failure_msg "No run directory defined for $NAME, cannot stop"
+                log_failure_msg "No run directory defined for $NAME (did you forget to set OPTIONS=\"-c -m /var/run/saslauthd\" in the defaults file?), not starting"
 		return 2
 	fi
 	PIDFILE=$RUN_DIR/saslauthd.pid
@@ -224,12 +247,18 @@ reload_instance()
 		NAME=default
 	fi
 
+	# Set OPTIONS to a default value, as noted in the defaults file
+	if [ -z "$OPTIONS" ]; then
+		log_warning_msg "Options (OPTIONS) undefined in $1, using default (-c -m /var/run/saslauthd)"
+		OPTIONS="-c -m /var/run/saslauthd"
+	fi
+
 	# Determine run directory and pid file location by looking
 	# for an -m option.
 	RUN_DIR=`echo "$OPTIONS" | xargs -n 1 echo | sed -n '/^-m$/{n;p}'`
 	if [ -z "$RUN_DIR" ]; then
 		# No run directory defined in defaults file, fail.
-        log_failure_msg "No run directory defined for $NAME, cannot reload"
+                log_failure_msg "No run directory defined for $NAME (did you forget to set OPTIONS=\"-c -m /var/run/saslauthd\" in the defaults file?), not starting"
 		return 2
 	fi
 	PIDFILE=$RUN_DIR/saslauthd.pid
@@ -252,6 +281,52 @@ reload_instance()
 	log_end_msg $?
 }
 
+# Function that sends a SIG0 to a single saslauthd instance
+# Parameters:
+#	$1 = path of default file for this instance
+# Return value:
+#	0 on success (does not mean the daemon was reloaded)
+#	other values on failure
+check_instance()
+{
+	# Load defaults file for this instance.
+	. $1
+
+	# If the short name of this instance is undefined, warn the user
+	# but choose a default name.
+	if [ -z "$NAME" ]; then
+		log_warning_msg "Short name (NAME) undefined in $1, using default"
+		NAME=default
+	fi
+
+	# Determine run directory and pid file location by looking
+	# for an -m option.
+	RUN_DIR=`echo "$OPTIONS" | xargs -n 1 echo | sed -n '/^-m$/{n;p}'`
+	if [ -z "$RUN_DIR" ]; then
+		# No run directory defined in defaults file, fail.
+        log_failure_msg "No run directory defined for $NAME, cannot check"
+		return 2
+	fi
+	PIDFILE=$RUN_DIR/saslauthd.pid
+
+	log_daemon_msg "Checking $DESC" "$NAME"
+
+	# Reload the daemon. First, see if it is already running.
+	start-stop-daemon --start --quiet --pidfile $PIDFILE \
+		--exec $DAEMON --test > /dev/null
+
+	if [ "$?" -eq "0" ]; then
+		# Not running, signal this and stop.
+		log_progress_msg "(not running)"
+		log_end_msg 3
+		return 3
+	fi
+
+	log_progress_msg "(running)"
+	log_end_msg $?
+	return 0
+}
+
 # Function that creates a directory with the specified
 # ownership and permissions
 # Parameters:
@@ -264,6 +339,7 @@ createdir()
 {
 	# In the future, use -P/-Z to have SE Linux enhancement
 	install -d --group="$2" --mode="$3" --owner="$1" "$4"
+	[ -x /sbin/restorecon ] && /sbin/restorecon "$4"
 }
 
 # Action switch
@@ -280,6 +356,10 @@ case "$1" in
 	restart)
 		do_stopall
 		do_startall
+		;;
+	status)
+		do_checkall
+		exit $?
 		;;
 	start-instance)
 		if [ -f /etc/default/$2 ]; then
